### ISSUE TITLE
permission denied on run.rb

### ISSUE THREAD

**Issue by enzo2** [robhanlon22/etherpad-lite-heroku#1]
What do you make of this?

app[web.1]:←[0m bash: ./run.rb: Permission denied

**Comment by robhanlon22** [comment]
my bad, probably a bad umask. i'll fix.

**Comment by robhanlon22** [comment]
Huh, that's interesting. git only maintains the execute bit. That's interesting. I checked out the repo with a umask of 022 instead of 077 and it looked like things were fine. Is run.rb executable in your clone?

**Comment by enzo2** [comment]
Ah, looks like it's not. "-rw-------" But I am pushing to heroku from windows and am unfamiliar with how the permission works here.

**Comment by enzo2** [comment]
Was able to change the permission with >git update-index --chmod=+x run.rb
