### ISSUE TITLE
WHich port

### ISSUE THREAD

**Issue by weitzman** [robhanlon22/etherpad-lite-heroku#3]
OK, I got this deployed to Heroku. How do I use it? Specifically, I try to go to port 9001 for my app and nothing is running there. Thanks for any help you can provide.

**Comment by robhanlon22** [comment]
Hey @weitzman, I no longer monitor this repository because I created it for a project at a company I am no longer affiliated with. From what I remember, this runs on port 80, like all other Heroku apps.
